/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.sl846.battleship;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;

/**
 * Plays the Battleship game.
 */
public class App {
  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;
  final AbstractShipFactory<Character> shipFactory;
  
  /**
   * Constructs the App with given Board, input source, and output stream.
   * 
   * @param theBoard    is the Board used in battleship game.
   * @param inputSource is the input source to read from.
   * @param out         is the output stream to print to.
   */
  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
    this.shipFactory = new V1ShipFactory();
  }

  /**
   * Gives a prompt to user, then read from user input for Placement.
   * 
   * @param prompt is the String to inform user on what to input.
   * @return the Placement corresponding to user input.
   * @throws IOException if user input cannot build a valid Placement.
   */
  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  /**
   * Places one ship on the Board.
   * 
   * @throws IOException if user input cannot build a valid Placement.
   */
  public void doOnePlacement() throws IOException {
    String prompt = "Where would you like to put your ship? ";
    Placement placement = readPlacement(prompt);
    Ship<Character> ship = shipFactory.makeDestroyer(placement);
    theBoard.tryAddShip(ship);
    BoardTextView view = new BoardTextView(theBoard);
    out.print(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException {
    Board<Character> board = new BattleShipBoard<>(10, 20);
    App app = new App(board, new InputStreamReader(System.in), System.out);
    app.doOnePlacement();
  }
}
